# Generated by Django 3.2 on 2021-04-06 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature', models.FloatField(validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(19)])),
                ('humidity', models.FloatField(validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(35)])),
                ('time_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
